feat: mesa 24.1
Description of changes:

- Upgrade to mesa 24.1
- Remove Broadcom fix backport since it's part of 24.1 release
- 'nouveau-experimental' vulkan driver is now just 'nouveau'
- disable Intel RayTracing on anything but x86_64 (it's not supported
  anywhere else)
- Few dependency definitions / updates to fix build issues
  - python3-pycparser
  - cbindgen
  - version bump for wayland-protocols
  - restrict proc-macro2 crate to `< 1.0.80` (fixes
    `error[E0658]: use of unstable library feature 'proc_macro_byte_character'`)
    - also restricting syn crate to `< 2.0.59` because of dependency conflict
      on proc-macro2
  - add 'paste' crate
- add new dri libs to defined output files